#!/bin/sh
#######Path Defination###############
User_DIR=$(cd "$(dirname "$0")";pwd)

OP_LIST_DIR=${User_DIR}/FF_STATION
CP_LIST_DIR=${User_DIR}/CP_STATION

if [ ! -e ${OP_LIST_DIR} ]; then
  mkdir -p ${OP_LIST_DIR}
fi

if [ ! -e ${CP_LIST_DIR} ]; then
  mkdir -p ${CP_LIST_DIR}/LCP
      mkdir -p ${CP_LIST_DIR}/FFCP
fi

TPG=0 #=0:LFSR,=1:ATPG
TEST_VEC=10 #0 00 # Number of Test patterns
TOOLMODE=4 #=1:Normal Scan test, =2:Multi-cycle Test, =3: Multi-cycle test with Seq OB, =4:Toggle Gate TPI

	CAPTURE=10 #the number of capture cycles
  OBRATE=0.2 #ratio of OP FF
  LCP_rate=0.01 #the ratio of Logic CPs in all logic gates
  CP_GROUP=1 #=1: the number of CPs selected at each iteration
  CP_TYPE=1 #control point types =1: TDT, =2: Inversion, =3: Just Toggle
	FFCP_rate=0.0	#the ration of FF-CPs in all FFs
  SKIP_CAP=3 #SKIP_CAP=3, the CP control starts from the third capture cycle.
  INTERVAL_CYCLE=1 #=1: the number of interval cycles

ulimit -s unlimited
rm -f *.dat
for CIRCUIT in s9234 #s13207 s15850 s38417 s38584 #b14s.osaka b15s.osaka b20s.osaka  #s9234 s13207 s15850 s38417 s38584  b14s.osaka b15s.osaka b20s.osaka #b20s.osaka #s15850 s35932 s38584 s38417 #s13207 #s1488 s5378 s9234 #s13207 #s9234 #s15850 s38417 #s38584 #b04s.osaka b05s.osaka b06.osaka b14s.osaka b15s.osaka b20s.osaka

do
rm -f lfsr*.dat ATPG.dat
rm -f ${CIRCUIT}_tgl_FF_input.dat
rm -f ${CIRCUIT}_tgl_ff_tpi.dat

  ln -s ./circuit/$CIRCUIT
  ln -s ./tpg/lfsr.dat

	if [ "$TPG" = "0" ];
	then
		rm -f ${CIRCUIT}_lfsr_pi.dat
		./tpg/lfsr $CIRCUIT $TEST_VEC ${CIRCUIT}_lfsr_pi.dat
		ln -s tmp.test ${CIRCUIT}_lfsr_pi.dat
	else
 		 ln -s ./ATPG/SA/Com1Test/"$CIRCUIT".tests ATPG.dat
	fi

  if [ ! -e ${OP_LIST_DIR}/${CIRCUIT} ]; then
    mkdir -p ${OP_LIST_DIR}/${CIRCUIT}
  fi

  if [ ! -e ${User_DIR}/OUTPUTS/CPI/${CAPTURE}_cycles/ ]; then
    mkdir -p ${User_DIR}/OUTPUTS/CPI/${CAPTURE}_cycles/
  fi


#	  for ff_sta_file in  ./FF_STATION/$CIRCUIT/TOPSIS #./FF_STATION/$CIRCUIT/BRANCH ./FF_STATION/$CIRCUIT/COMPLEX ./FF_STATION/$CIRCUIT/TYPE_1 ./FF_STATION/$CIRCUIT/TYPE_2 ./FF_STATION/$CIRCUIT/TYPE_3 ./FF_STATION/$CIRCUIT/TOPSIS
# you can evaluate multiple FF OP list in one simulation by specifying the path of OB-FF List
	 cnt1=0
 for ff_sta_file in  ~/renesas/tpi4share/OPI/$CIRCUIT/TOPSIS
  #  for ff_sta_file in  ~/renesas/Renesas-TPI/Seq_FF_OPI/DATA/cp_$CIRCUIT/FF_STATION/TOPSIS
	   do

		if [ -e $ff_sta_file ];
		then
 		 echo === OB_STATION INFO of $ff_sta_file is FOUND, CONTINUE THE FAULT SIM PROCESS===
		else
 		 echo === NO OB_STATION INFO, PLEASE BACK TO FF_SELECTION PROCESS to Generate $ff_sta_file===
			exit
		fi

		ln -s ${ff_sta_file} ff_station_${cnt1}.dat
		let cnt1=${cnt1}+1
	 done


for CP_CTRL in 1 #3 #0 2 3 #2 3 #4
#=0:non CP control, =1: Logic gate toggling,=2:FF toggling, =3: applying random pattern to FF-CPs, =4: applying random patterns to Logic CPs
do
## when CP runs in random loading mode, the random patterns will be pre-generated by the following Setting
	if [ "$CP_CTRL" = "3" ];
		then
 		 echo === Generate the LFSR Vectors 4 FF_CPI===
			./tpg_TPI_ff/lfsr_ff $CIRCUIT $TEST_VEC $FFCP_rate $CAPTURE ${CIRCUIT}_tgl_ff_tpi.dat
		ln -s tmp_ff.dat ${CIRCUIT}_tgl_ff_tpi.dat

	elif [ "$CP_CTRL" = "4" ];
		then
 		 echo ===  Generate the LFSR Vectors 4 Logic_CPI===
			./tpg_TPI_gate/lfsr_gt $CIRCUIT $TEST_VEC $LCP_rate $CAPTURE tgl_gt_tpi.dat
			ln -sf tmp_gt.dat tgl_gt_tpi.dat
 		 echo ===  end ===
	fi

	if [ "$CP_CTRL" = "1" ] || [ "$CP_CTRL" = "4" ];
	then
    echo ==simulation for Logic CPI === #>> $LOG_FILE

  #  CP_LIST=0 # =0: normal

# ln -s ${CP_LIST_DIR}/LCP/${CIRCUIT}/rlcp_$CP_GROUP  tgl_gt_input.dat
 #ln -s ../nakaoka_cp/20201106_2/CP_STATION/${CIRCUIT} tgl_gt_input.dat

ln -s ~/renesas/tpi4share/Logic-CPI_by_rtpi/${CIRCUIT}/DC202002 tgl_gt_input.dat

	echo ===$CIRCUIT: $CP_GROUP $INTERVAL_CYCLE===========
			time ./lbistsim $CIRCUIT $TOOLMODE $TPG $CP_CTRL $LCP_rate $CAPTURE $INTERVAL_CYCLE $SKIP_CAP $cnt1 $OBRATE $CP_GROUP $TEST_VEC $CP_TYPE #>> ${User_DIR}/$CIRCUIT.log
  echo ===logic CPI simulation process end=== #>> $LOG_FILE
	rm -rf tgl_gt_input.dat

	else
    	echo ==Simulation for FF-CPI=== #>> $LOG_FILE

  ln -s ${CP_LIST_DIR}/FFCP/${CIRCUIT}/rffcp  ${CIRCUIT}_tgl_FF_input.dat

	echo ===$CIRCUIT: Interval capture = $INTERVAL_CYCLE===========

			time ./lbistsim $CIRCUIT $TOOLMODE $TPG $CP_CTRL $FFCP_rate $CAPTURE $CYCLE $SKIP_CAP $FF_SEL_METHOD $cnt1 $OBRATE $TEST_VEC #>> Switch_ctr.txt

    echo ==FF CPI simulation process end=== #>> $LOG_FILE

		rm -rf tgl_*.dat ff_station_*
	fi

done
rm -f ${CIRCUIT}_tgl_FF_input.dat
rm -f ${CIRCUIT}_tgl_ff_tpi.dat
rm -f ff_station_*
    if [ -e fault_list.dat ];
      then
      mv fault_list.dat "$CIRCUIT"_fault_list.dat
      if [ ! -e ./fault_list ];
        then
        mkdir fault_list
      fi
      mv "$CIRCUIT"_fault_list.dat ./fault_list
    fi
#if exist fault list file -end-
#rm -f #ff_station* tgl_* nfs*
rm -f $CIRCUIT lfsr.dat *~ tmp*  ff_station.dat ATPG.dat *lfsr_pi.dat
done
