#include <stdio.h>
#include <stdlib.h>

#define BUF_MAX 20
#define PHASE_SHIFT 1
#define LTRTPG 0 //1:test pattern generated by LTRTPG 
#define K 3 //k value of LTRTPG

void phase_shifter(int Y[], int nfin);
void LT_RTPG(int X[],int RTPG[],int TFF[],int nfin);

int main(int argc, char *argv[]){
  int i,ia, ib, max, test_vec, nfin;
  int XOR[10];
  char buf[BUF_MAX];
  FILE *fin, *fout;

  if(argc < 3){
    printf("error: too less arguments!\n");
    exit(1);
  }

  fin = fopen(argv[1], "r");
  if(fin == NULL){
    printf("error: '%s' is not found\n", argv[1]);
    exit(1);
  }
  fscanf(fin, "%d %d %d", &nfin, &nfin, &nfin);
  fclose(fin);

  fin = fopen("lfsr.dat", "r");
  if(fin == NULL){
    printf("error: 'lfsr.dat' is not found\n");
    exit(1);
  }
  fscanf(fin, "%d", &max);

  if(nfin > max){
    printf("error: too many fins!\n");
    fclose(fin);
    exit(1);
  }

  for(ia=0; ia<nfin; ia++)
    if(fgets(buf, BUF_MAX, fin) == NULL){
      printf("error: too many fins!\n");
      fclose(fin);
      exit(1);
    }
  fscanf(fin, "%d", &XOR[0]);
  for(ia=1; ia<=XOR[0]; ia++)
    fscanf(fin, "%d", &XOR[ia]);
  fclose(fin);

  int X[nfin+1];

#if PHASE_SHIFT
  int Y[nfin+1];
#endif

 test_vec = atoi(argv[2]);
fout = fopen("tmp.test", "w");
  fprintf(fout, "%d %d\n", test_vec, nfin);
  

  for(ia=0; ia<nfin; ia++)
    X[ia] = 1;

#if PHASE_SHIFT
  for(ia=0; ia<nfin; ia++)
    Y[ia] = X[ia];

  phase_shifter(Y, nfin);

  for(ia=0; ia<nfin; ia++)
    fprintf(fout, " %d", Y[ia]);
#else
  for(ia=0; ia<nfin; ia++)
    fprintf(fout, " %d", X[ia]);
#endif
  fprintf(fout, "\n");

 
#if LTRTPG  
  int RTPG[nfin+1];
	int TFF[nfin];
	FILE *fPTRGout;
for(ia=0; ia<nfin; ia++){
    RTPG[ia] = 1;
	TFF[ia]=1;}
fPTRGout = fopen("LT_RTPG.dat", "w");
 fprintf(fPTRGout, "testnum=%d bit length=%d K=%d\n", test_vec,nfin,K);
for(i=0;i<nfin;i++)
	fprintf(fPTRGout, " %d", TFF[i]);
fprintf(fPTRGout, "\n");
#endif

  for(ia=1; ia<test_vec; ia++){
    for(ib=nfin; ib>=1; ib--)
      X[ib] = X[ib-1];

    for(ib=1; ib<XOR[0]; ib++)
      X[XOR[ib+1]] ^= X[nfin];
    X[0] = X[nfin];

#if LTRTPG   
for(i=0; i<nfin; i++)
RTPG[i]=X[i];
//RTPG[i]=(~X[i])&1;
	LT_RTPG(X,RTPG,TFF,nfin);
//printf("here?\n");
	for(i=0;i<nfin;i++)
	fprintf(fPTRGout, " %d", TFF[i]);
	fprintf(fPTRGout, "\n");
#endif
 
#if PHASE_SHIFT
    for(ib=0; ib<nfin; ib++)
      Y[ib] = X[ib];

    phase_shifter(Y, nfin);

    for(ib=0; ib<nfin; ib++)
      fprintf(fout, " %d", Y[ib]);
#else
    for(ib=0; ib<nfin; ib++)
      fprintf(fout, " %d", X[ib]);
#endif
    fprintf(fout, "\n");
}
  fprintf(fout, "END\n");
#if LTRTPG
fclose(fPTRGout);
#endif
  fclose(fout);

  return 0;
}

void phase_shifter(int X[], int nfin){
  int ia;
  for(ia=1; ia<nfin; ia++)
    X[ia] ^= X[ia-1];
}

void LT_RTPG(int X[],int RTPG[],int TFF[],int nfin){
	int ix,ik;
	for(ix=0;ix<nfin;ix++){//RTPG[ix]=X[ix];
		for(ik=ix+1;ik<ix+K;ik++){
			if(ik>=nfin) RTPG[ix]&=X[ik-nfin];
			else RTPG[ix]&=X[ik];
			}
		//if(RTPG[ix]==0) TFF[ix]=X[ix];
		if(RTPG[ix]==1) TFF[ix]=(~TFF[ix])&1;
	}

}

